# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  # Uncomment and add these steps to a job if gradle is needed to be available instead of only ./gradlew
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: Install gradle
    #  run: |
    #    wget https://downloads.gradle-dn.com/distributions/gradle-6.7.1-bin.zip
    #    unzip -d /opt/gradle gradle-6.7.1-bin.zip
    #    /opt/gradle/gradle-6.7.1/bin/gradle -v
    #- name: Install gradle wrapper
    #  working-directory: ./td-racing-remake/
    #  run: /opt/gradle/gradle-6.7.1/bin/gradle wrapper


  test:
    needs:
    - setup
    runs-on: ubuntu-latest
    container:
      # Image that supports the specified android API
      # (https://hub.docker.com/r/fabernovel/android/tags?page=1&ordering=last_updated)
      image: docker://fabernovel/android:api-30-v1.3.0

    steps:
    - uses: actions/checkout@v2
    - name: Run tests (via Makefile)
      working-directory: ./td-racing-remake/
      run: make test


  build:
    needs:
    - setup
    runs-on: ubuntu-latest
    container:
      # Image that supports the specified android API
      # (https://hub.docker.com/r/fabernovel/android/tags?page=1&ordering=last_updated)
      image: docker://fabernovel/android:api-30-v1.3.0

    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle the desktop binary (via Makefile)
      working-directory: ./td-racing-remake/
      run: make dist_desktop
    - name: Build with Gradle the html directory (via Makefile) which needs the program zip
      working-directory: ./td-racing-remake/
      run: |
        apt update
        apt install zip
        make dist_html
    # Do not build the release apk since this apk needs to be signed with a
    # private keystore and private credentials
    - name: Build with Gradle the android debug APK (via Makefile)
      working-directory: ./td-racing-remake/
      run: make build_android_debug
    - name: Build with Gradle the JavaDoc documentations
      working-directory: ./td-racing-remake/
      run: make doc
    # This is used to share all created "binary" files between the separated jobs
    - name: Temporarily save created "binary" files
      uses: actions/upload-artifact@v2
      with:
        name: binary-artifacts
        path: |
          ./td-racing-remake/bin/
          ./td-racing-remake/javadoc/
        retention-days: 7

  deploy:
    needs:
    - setup
    - build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Retrieve temporarily saved "binary" files from the build job
      uses: actions/download-artifact@v2
      with:
        name: binary-artifacts
        path: |
          ./td-racing-remake/bin/
          ./td-racing-remake/javadoc/
    - name: Create website
      working-directory: ./web-page
      run: make
    - name: Deploy to GitHub Pages
      # Only deploy the website when pushing on the main branch
      if: github.ref == 'refs/heads/main'
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: ./web-page/bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
